### DISCUSSION TITLE
Avoid automatically adding the @keyframes within <GlobalStyles />

### DISCUSSION THREAD

**Discussion by kelvindecosta** [ben-rogerson/twin.macro#295] [Q&A] [answered]
Hey everyone!

As far as I know, a setup using Styled Components doesn't require a utility like PurgeCSS.
Only components that are rendered have their styles generated in the build.

I was just wondering whether this is the same for my setup.
I am using `twin.macro` in a Gatsby site alongside `styled-components`.
I haven't added any `purge` patterns in `tailwind.config.js`.

I noticed the following styles in the final build of a blank site, one without any user-defined styles:

```css
@-webkit-keyframes spin{to{-webkit-transform:rotate(360deg);-ms-transform:rotate(360deg);transform:rotate(360deg);}}/*!sc*/
@keyframes spin{to{-webkit-transform:rotate(360deg);-ms-transform:rotate(360deg);transform:rotate(360deg);}}/*!sc*/
@-webkit-keyframes ping{75%,100%{-webkit-transform:scale(2);-ms-transform:scale(2);transform:scale(2);opacity:0;}}/*!sc*/
@keyframes ping{75%,100%{-webkit-transform:scale(2);-ms-transform:scale(2);transform:scale(2);opacity:0;}}/*!sc*/
@-webkit-keyframes pulse{50%{opacity:.5;}}/*!sc*/
@keyframes pulse{50%{opacity:.5;}}/*!sc*/
@-webkit-keyframes bounce{0%,100%{-webkit-transform:translateY(-25%);-ms-transform:translateY(-25%);transform:translateY(-25%);-webkit-animationTimingFunction:cubic-bezier(0.8,0,1,1);animationTimingFunction:cubic-bezier(0.8,0,1,1);}50%{-webkit-transform:none;-ms-transform:none;transform:none;-webkit-animationTimingFunction:cubic-bezier(0,0,0.2,1);animationTimingFunction:cubic-bezier(0,0,0.2,1);}}/*!sc*/
@keyframes bounce{0%,100%{-webkit-transform:translateY(-25%);-ms-transform:translateY(-25%);transform:translateY(-25%);-webkit-animationTimingFunction:cubic-bezier(0.8,0,1,1);animationTimingFunction:cubic-bezier(0.8,0,1,1);}50%{-webkit-transform:none;-ms-transform:none;transform:none;-webkit-animationTimingFunction:cubic-bezier(0,0,0.2,1);animationTimingFunction:cubic-bezier(0,0,0.2,1);}}/*!sc*/
```

This is my current configuration:

```js
// tailwind.config.js
module.exports = {
  purge: [],
  darkMode: false,
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

```js
// babel-plugin-macros.config.js
module.exports = {
  twin: {
    preset: "styled-components",
  },
}
```

```js
// gatsby-config.js
module.exports = {
  plugins: [`gatsby-plugin-styled-components`]
}
```

```js
// src/components/layout/index.js
import React from "react"
import { GlobalStyles } from "twin.macro"

const Layout = ({ children }) => (
  <>
    <GlobalStyles />
    {children}
  </>
)

export default Layout
```

Any help with clarifying this matter is appreciated.
Thanks!
