### DISCUSSION TITLE
Can twin.macro using with the custom class

### DISCUSSION THREAD

**Discussion by hoangddt** [ben-rogerson/twin.macro#538] [Q&A] [answered]
I have a custom css file named "button.scss" like this:

``` scss
.btn {
  @apply px-3 py-2 rounded font-semibold inline-flex text-sm items-center;
  
  &.btn-large {
    @apply px-6 py-3 text-lg;
  }
  &.btn-sm {
    @apply px-2 py-1;
  }
  &:hover {
    text-decoration: none;
  }
}

.btn-primary{
  @apply bg-primary text-white;
  &:hover {
    background: darken($primary, 10);
  }
}
```

And the declaration of twin.macro like this:

``` javascript
import tw, { styled, theme } from 'twin.macro';
export const Button = styled.button({
  ...tw`btn`,
  variants: {
    variant: {
      primary: tw`btn-primary`,
      secondary: tw`btn-secondary`
    }
  }
});
```

The console report error:
```
error - ./src/designsystem/Button.js
MacroError:

✕ btn was not found
    at Array.reduce (<anonymous>)
    at Array.forEach (<anonymous>)
```

Besides the css of tailwind, can the css class that we write ourself can be use?
