### DISCUSSION TITLE
Does purge also work when using twin?

### DISCUSSION THREAD

**Discussion by jahirfiquitiva** [ben-rogerson/twin.macro#568] [Q&A]
Hello, I wanted to ask if the tailwind  purge feature to remove unused styles still works if I use twin, and if so, do I have to setup something? or will it work right away?

thanks

**Comment by ben-rogerson** [comment]
Hey there,

Purge is not required with twin - no need for setup.

**Reply by jahirfiquitiva** [reply]
what does "is not required" mean? 🤔 how is that? 🤔

**Reply by ben-rogerson** [reply]
Twin changes the tailwind classes to css objects, then those objects are passed to your css-in-js package. It's up to that package (emotion/styled-components/etc) to work with the css objects from that point.

**Reply by steveadams** [reply]
Hi @ben-rogerson , I hope there are no stupid questions here!

I'm wondering - does twin essentially create "applied" tailwind styles, so the classes aren't reused? While purging isn't necessary, you don't benefit from reusing classes either - each call to `tw` yields a new object using the styles from the given classes, and not a reference to them?

**Reply by jahirfiquitiva** [reply]
I was giving a look at the generated css for my website and noticed that while there's a bunch of css that needs to stay (variables mostly), there's a lot of classes that are still in there, even when (as @steveadams mentioned) it looks like `tw` yields the styled component replacing tailwind classes with the actual css, and the tailwind classes are unused 🤔

Like, my generated css includes this:
```css
.pointer-events-none {
  pointer-events: none;
}
.pointer-events-auto {
  pointer-events: auto;
}
```

but, what I understand with `tw` is that this:
```typescript
const StyledThing = tw.div`
    pointer-events-none
    md:(pointer-events-auto)
`
```

gets transformed into something like

```css
.css-123 {
    pointer-events: none;
}

@media screen and (min-width: 420px) {
    .css-123 {
        pointer-events: auto;
    }
}
```

and

```html
<div class="css-123">...</div>
```

So, I don't see the need to still have the tailwind classes in the generated css.

I may be wrong, but this is what I'm seeing.
