### ISSUE TITLE
Invalid transform scale variables break transitions

### ISSUE THREAD

**Issue by klittlepage** [ben-rogerson/twin.macro#220]
Thanks so much for your work on v2 🎉 

A transition such as `transition-transform duration-500 hover:transform hover:scale-125` generates:

```css
.css-1hbbcmi-Profile {
  -webkit-transition-property: -webkit-transform;
  -webkit-transition-property: transform;
  transition-property: transform;
  -webkit-transition-timing-function: cubic-bezier(0.4,0,0.2,1);
  transition-timing-function: cubic-bezier(0.4,0,0.2,1);
  -webkit-transition-duration: 500ms;
  transition-duration: 500ms;
}

.css-1hbbcmi-Profile:hover {
  --tw-translate-x: 0;
  --tw-translate-y: 0;
  --tw-rotate: 0;
  --tw-skew-x: 0;
  --tw-skew-y: 0;
  --tw-scale-x: 1;
  --tw-scale-y: 1;
  -webkit-transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  -ms-transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  transform: translateX(var(--tw-translate-x)) translateY(var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y));
  --tw-transform-scale-x: 1.25;
  --tw-transform-scale-y: 1.25;
}
```

We need to change `--tw-transform-scale-{x,y}` to `--tw-scale-{x,y}`. I'm opening a PR to do so.
