### ISSUE TITLE
Why isn't .container supported?

### ISSUE THREAD

**Issue by corysimmons** [ben-rogerson/twin.macro#40]
Super curious what the technical hangup was on that.

**Comment by ben-rogerson** [comment]
Not much of a story, just haven't had the chance to do it 🤷

**Comment by ben-rogerson** [comment]
I think we just need to generate a js object of this from `screens` in config:

```css
.container {
  width: 100%
}

@media (min-width: 640px) {
  .container {
    max-width: 640px
  }
}

@media (min-width: 768px) {
  .container {
    max-width: 768px
  }
}

@media (min-width: 1024px) {
  .container {
    max-width: 1024px
  }
}

@media (min-width: 1280px) {
  .container {
    max-width: 1280px
  }
}
```
