### ISSUE TITLE
@apply and @screen in plugins not working as expected

### ISSUE THREAD

**Issue by brc-dd** [ben-rogerson/twin.macro#432]
### Description

I am unable to use `@apply` and `@screen` in my custom plugins. The `@apply` is being completely ignored, and the order of `@screen` keys is not being respected.

Even if I replace `@screen sm` with `@media (min-width: 640px)` (and others too), the plugin is not working as expected. Although for `@apply`, as a possible workaround, I am able to define CSS directly in the plugin or combine multiple classes directly using `tw`.

---

### My Plugin

```js
plugin(({ addComponents }) =>
  addComponents({
    ".componentX": {
      "@apply w-full mx-auto px-4 bg-black text-white py-8": {},
      "@screen sm": { maxWidth: "540px" },
      "@screen md": { maxWidth: "720px" },
      "@screen lg": { maxWidth: "960px" },
      "@screen xl": { maxWidth: "1140px" },
      "@screen 2xl": { maxWidth: "1320px" },
    },
  })
)
```

### JSX Code

```jsx
<>
  <div tw="componentX">Hey There</div>              {/* Actual */}
  <div className="componentX">Hey There</div>       {/* Expected */}
</>
```

---

### Actual vs Expected Behavior

![image](https://user-images.githubusercontent.com/40380293/118086743-10287600-b3e2-11eb-8b6d-7c849f6e7dc6.png)

#### Actual

```css
@media (min-width: 1536px) {
  .css-154dcof {
    max-width: 1320px;
  }
}
@media (min-width: 1280px) {
  .css-154dcof {
    max-width: 1140px;
  }
}
@media (min-width: 1024px) {
  .css-154dcof {
    max-width: 960px;
  }
}
@media (min-width: 768px) {
  .css-154dcof {
    max-width: 720px;
  }
}
@media (min-width: 640px) {
  .css-154dcof {
    max-width: 540px;
  }
}
````

#### Expected

The media queries should have been in reverse order, i.e. in which the keys of the plugin are defined. And there should have been styles corresponding to `w-full mx-auto px-4 bg-black text-white py-8` also.

---

### Minimum Reproducible Example

https://github.com/brc-dd/twin-possible-bug

This repo is bootstrapped using the official Next.js example: [with-tailwindcss](https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss) followed by configuring it to use `twin.macro` as per the instructions [given here](https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion#getting-started).
