### ISSUE TITLE
`@screen` and `@media` in plugins not working as expected

### ISSUE THREAD

**Issue by brc-dd** [ben-rogerson/twin.macro#433]
### Description

I am unable to use `@screen` in my custom plugins properly. The order of `@screen` keys is not being respected. Even if I replace `@screen sm` with `@media (min-width: 640px)` (and others too), the plugin is not working as expected. 

---

### My Plugin

```js
plugin(({ addComponents }) =>
  addComponents({
    ".componentX": {
      width: "100%",
      margin: "0 auto",
      padding: "2rem 1rem",
      background: theme("colors.black"),
      color: "white",
      "@screen sm": { maxWidth: "540px" },
      "@screen md": { maxWidth: "720px" },
      "@screen lg": { maxWidth: "960px" },
      "@screen xl": { maxWidth: "1140px" },
      "@screen 2xl": { maxWidth: "1320px" },
    },
  })
)
```

### JSX Code

```jsx
<>
  <div tw="componentX">Hey There</div>              {/* Actual */}
  <div className="componentX">Hey There</div>       {/* Expected */}
</>
```

---

### Actual vs Expected Behavior

![image](https://user-images.githubusercontent.com/40380293/118445885-99a2b580-b70c-11eb-812c-0636fecb0211.png)

#### Actual

```css
@media (min-width: 1536px) {
  .css-154dcof {
    max-width: 1320px;
  }
}
@media (min-width: 1280px) {
  .css-154dcof {
    max-width: 1140px;
  }
}
@media (min-width: 1024px) {
  .css-154dcof {
    max-width: 960px;
  }
}
@media (min-width: 768px) {
  .css-154dcof {
    max-width: 720px;
  }
}
@media (min-width: 640px) {
  .css-154dcof {
    max-width: 540px;
  }
}
````

#### Expected

The media queries should have been in reverse order, i.e. in which the keys of the plugin are defined. 

---

### Minimum Reproducible Example

https://github.com/brc-dd/twin-possible-bug/tree/media-query-bug

```sh
git clone -b media-query-bug https://github.com/brc-dd/twin-possible-bug; yarn; yarn build; yarn start
```

This repo is bootstrapped using the official Next.js example: [with-tailwindcss](https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss) followed by configuring it to use `twin.macro` as per the instructions [given here](https://github.com/ben-rogerson/twin.examples/tree/master/next-emotion#getting-started).

Migrated from #432
