### ISSUE TITLE
Cannot add multiple variants of a font-face to base layer via plugins

### ISSUE THREAD

**Issue by abhishekdev** [ben-rogerson/twin.macro#603]
**Issue Summary**

If multiple `@font-face` definitions are added to the base layer of tailwind, only the first definition remains when using twin.macro

**Why is this an issue**
- The output (base global styles) for `twin.macro@v2.8.1` is different from `tailwindcss@2.2.19`.
- A custom font may require different definitions for its different styles/weights/file types etc.
- The object format for adding plugins is not viable option as the `@font-face` key cannot be repeated in config object.
- Apart from object based config, Tailwind also supports parsing CSS in the plugins via postcss. This approach is used for adding preflight is base layer. ([refer tailwindcss code here](https://github.com/tailwindlabs/tailwindcss/blob/808e69b36027e1eed3e51591c258e181d719cb6f/src/corePlugins.js#L177-L179))
- Since `@font-face` definitions can repeat, it seems like a viable option to add multiple fonts to a sharable tailwindcss config via a plugin. Instead of the [CSS processor  approach](https://v2.tailwindcss.com/docs/adding-base-styles#font-face-rules)

For a given plugin lik ethe following 
```js
import postcss from 'postcss';

export default plugin(function customFontFaces({ addBase }) {
    // Emulate loading multiple font faces as a string
    // The string could be sourced from an actual css file (just like in tailwind preflight)
    // ref: https://github.com/tailwindlabs/tailwindcss/blob/808e69b36027e1eed3e51591c258e181d719cb6f/src/corePlugins.js#L177-L179
    const mutipleFontFaces = `
  @font-face {
    src: url('./fonts/myfont1.ttf');
    font-style: normal;
    font-weight: 400;
    font-family: MyFont1;
  }
  @font-face {
    src: url('./fonts/myfont1-semibold.ttf');
    font-style: normal;
    font-weight: 500;
    font-family: MyFont1;
  }
  @font-face {
    src: url('./fonts/myfont2.ttf');
    font-style: normal;
    font-weight: 400;
    font-family: MyFont2;
  }
`
    addBase(postcss.parse(mutipleFontFaces).nodes);
});
```

**Twin.Macro output -- the issue (❌)**
```css
  @font-face {
    src: url('./fonts/myfont1.ttf');
    font-style: normal;
    font-weight: 400;
    font-family: MyFont1;
  }
```

**Expected output**
> This is not an issue wiith tailwindcss, as it generates this output when triggered directly (e.g. via CLI)

```css
  @font-face {
    src: url('./fonts/myfont1.ttf');
    font-style: normal;
    font-weight: 400;
    font-family: MyFont1;
  }
  @font-face {
    src: url('./fonts/myfont1-semibold.ttf');
    font-style: normal;
    font-weight: 500;
    font-family: MyFont1;
  }
  @font-face {
    src: url('./fonts/myfont2.ttf');
    font-style: normal;
    font-weight: 400;
    font-family: MyFont2;
  }
```

**Possible Root cause**
- It seems this is related to how `twin.macro` parses the rules added by plugin in this line https://github.com/ben-rogerson/twin.macro/blob/a30a5682dda7485bb1353d2ca895084e63bae334/src/utils/getUserPluginData.js#L162-L164
- The `deepMerge` from lodash ends up retaining only the first definition of font face.

**Workaround**
- Define in GlobalStyles per project. 
  - Fine for single projects. However, non-optimal when intent is to share a tailwindcss config across projects.
- e.g. for `@emotion/react`
```jsx
import { css, Global } from '@emotion/react';

const mutipleFontFaces = `
  @font-face {
    src: url('./fonts/myfont1.ttf');
    font-style: normal;
    font-weight: 400;
    font-family: MyFont1;
  }
  @font-face {
    src: url('./fonts/myfont1-semibold.ttf');
    font-style: normal;
    font-weight: 500;
    font-family: MyFont1;
  }
  @font-face {
    src: url('./fonts/myfont2.ttf');
    font-style: normal;
    font-weight: 400;
    font-family: MyFont2;
  }
`

<Global styles={css(mutipleFontFaces)} />
```

**Further discussion**
- It seems the data structure needs to account for multiple definitions and allow any configured minifiers (in postcss) to remove any seemingly redundant selectors. Thoughts?
- I added a [test case on a fork](https://github.com/abhishekdev/twin.macro/commit/d1a427db9cc649884a6ae1f1d8cd5537867c2976#diff-39382b61c0f3c6510d86b1c9feec9d6a5bd32cc9487ca69e09767bf625fd002eR11358-R11364).
- The issue can be inferred from the generated snapshot https://github.com/abhishekdev/twin.macro/blob/d1a427db9cc649884a6ae1f1d8cd5537867c2976/__snapshots__/plugin.test.js.snap#L11357-L11364
