### ISSUE TITLE
@tailwindcss/typography nextjs emotion css error

### ISSUE THREAD

**Issue by cs50victor** [ben-rogerson/twin.macro#640]
I ran into this issue when I tried using the @tailwindcss/typography plugin with mdx-bundler to create a blog post. 

I'm making use of nextjs + twin.macro(emotion) + mdx-bundler.

The typography classes are being mixed up 

```css
<style data-emotion="css l2qb0n-ArticleContainer">
              .css-l2qb0n-ArticleContainer {
                display: block;
                max-width: 65ch;
                font-family: Radial, SF Pro Text, -apple-system, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
                --tw-prose-body: #3f3f46;
               .........
                font-size: 1rem;
                line-height: 1.75;
                color: var(--tw-prose-body);

                :where(ul ul {
                    margin-top:0.75em; margin-bottom:0.75em;
                  }

                  :where(blockquote p:last-of-type):not(:where([class~="not-prose"] *))::after {
                    content:close-quote;
                  }

                  :where(blockquote p:first-of-type):not(:where([class~="not-prose"] *))::before {
                    content:open-quote;
                  }

                  @media (prefers-color-scheme: dark) {
                    --tw-prose-body:var(--tw-prose-invert-body); --tw-prose-headings:var(--tw-prose-invert-headings); --tw-prose-lead:var(--tw-prose-invert-lead); --tw-prose-links:var(--tw-prose-invert-links); --tw-prose-bold:var(--tw-prose-invert-bold); --tw-prose-counters:var(--tw-prose-invert-counters); --tw-prose-bullets:var(--tw-prose-invert-bullets); --tw-prose-hr:var(--tw-prose-invert-hr); --tw-prose-quotes:var(--tw-prose-invert-quotes); --tw-prose-quote-borders:var(--tw-prose-invert-quote-borders); --tw-prose-captions:var(--tw-prose-invert-captions); --tw-prose-code:var(--tw-prose-invert-code); --tw-prose-pre-code:var(--tw-prose-invert-pre-code); --tw-prose-pre-bg:var(--tw-prose-invert-pre-bg); --tw-prose-th-borders:var(--tw-prose-invert-th-borders); --tw-prose-td-borders:var(--tw-prose-invert-td-borders);
                  }

                  margin-left:auto; margin-right:auto; padding-left:1.5rem; padding-right:1.5rem; margin-top:1rem; margin-bottom:1rem; label:ArticleContainer;
                }

                ;
              }
```

I've tried everything, from downgrading both package versions to adding postcss as a dependency, but nothing fixed the issue. Has anyone else faced this problem? @ben-rogerson
