### ISSUE TITLE
twin.macro v3 introduces new unwanted styles with GlobalStyles object

### ISSUE THREAD

**Issue by zsombor-guti** [ben-rogerson/twin.macro#773]
Hello!

I've upgraded to twin.macro 3.1.0 a few days ago on an internal UI library and started noticing a few weird things, the main one being that my coloured-background buttons disappeared.
After investigating, I've found that the `GlobalStyles` object introduces a few weird styles, which it didn't before. The cause of this is the following part:

```css
button, [type='button'], [type='reset'], [type='submit'] {
    -webkit-appearance: button;
    background-color: transparent;
    background-image: none;
}
```

I have tried playing around with the `tailwindcss` version but nothing seemed to have an effect, only if I dropped my `twin.macro` version back to 2.8.2.
I am also using `styled-components`, which is currently at version 5.3.6. 

My GlobalStyles config (which is exported from the UI library and imported into the app's `app.jsx` file):

```tsx
import React from "react";
import { createGlobalStyle } from "styled-components";
import tw, { theme, GlobalStyles as BaseStyles } from "twin.macro";

const CustomStyles = createGlobalStyle`...`;

export const GlobalStyles = () => (
	<>
		<BaseStyles />
		<CustomStyles />
	</>
);
```

Was this change intentional? How can I turn off these extra styles? I would only need the default `@tailwind` styles.
